on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call: {}

name: Check

permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: false
      - name: Go generate check
        run: |
          set -x
          go generate ./...

          if [ -n "$(git status --porcelain)" ]; then
            git status --porcelain
            echo 'go generate is out of date'
            exit 1
          fi
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=30m
      - name: Go build
        run: go build -o "$(mktemp -d)/fox" ./cmd  
      - name: Go test
        run: go test ./...
