on:
  push:
    branches: [main]

name: Release

concurrency:
  group: release
  cancel-in-progress: true

env:
  RELEASE_NAME: ''
  RELEASE_TAG: ''

permissions:
  contents: write

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
  release:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: |
          echo "RELEASE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(./version.sh)" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: ./allbuild.sh
        env:
          GOLDFLAGS: -s -w
      - name: Release add
        uses: ncipollo/release-action@v1.18.0
        with:
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_TAG }}
          commit: ${{ github.sha }}
          artifacts: ./pkg/*
          allowUpdates: true
          artifactErrorsFailBuild: true
          omitBody: true
          omitBodyDuringUpdate: true
          removeArtifacts: true
